auctionhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.urls import login, logout, register
from news.models import News, Review
from catalogue import urls as catalogue_urls
from catalogue.views import view_all, view_era, view_one
from catalogue.models import Catalogue
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('register', register, name="register"),
    path('', include('news.urls')),
    url(r'^auctions/', include(catalogue_urls)),
    path('', include('payment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from .views import view_all, view_era, view_one
from .models import Catalogue

app_name = 'catalogue'
urlpatterns = [      
    url(r'^$', view_all, name="catalogue-all"),      
    url(r'^era(\d+)', view_era, name='view_era'),      
    url(r'^item/(\d+)', view_one, name="catalogue-one")
] 

home/urls.py
from django.urls import path
from .views import index, about, contact, faq, how_to, shipping
from catalogue.models import Catalogue

app_name = 'home'
urlpatterns = [
    path('', index, name="index"),
    path('about', about, name="about"),
    path('contact', contact, name="contact"),
    path('FAQ', faq, name="faq"),
    path('how-to', how_to, name="how_to"),
    path('shipping', shipping, name="shipping"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from catalogue.models import Catalogue
from news.models import News

def index(request):
    """Return the index.html file."""
    newest_picture = Catalogue.objects.exclude(sale_status=True).last()
    top_two_blogs = News.objects.all()[:2]
    context = {
        "newest_picture": newest_picture,
        "top_two_blogs": top_two_blogs
    }
    return render(request, 'index.html', context)


def about(request):
    """Background info on the company."""
    return render(request, 'about.html')


def contact(request):
    """Contact details for the company."""
    return render(request, 'contact.html')


def faq(request):
    """General information about the company and the website."""
    return render(request, 'faq.html')


def how_to(request):
    """Instructions onhow to use the bidding function."""
    return render(request, 'how-to.html')


def shipping(request):
    """Customer advice on shipping."""
    return render(request, 'shipping.html')

home/templates/about.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}About Gray and Sons{% endblock %}
{% block page_heading %}About Us{% endblock %}
{% block content %}

<div class="container-fluid">
    <p>Gray's is a family business that was founded London in 1890. Originally a portrait gallery the business expanded to include first other forms of art then furniture and by the 1950's had become an auction house specialising in antiques.</p>
    <p>Possibly owing to our origin we specialise in British antiques and artifacts of the Victorian age. We do however have various other items of differing eras and origins from time to time, so please do feel welcome to browse our collection.</p>
    <p>We regularly update our blog to keep you informed of our new stock, and highlight anything unusual we have to offer on the front page of our website as it becomes available.</p>
    <p>Enjoy browsing our collection, I do hope you find something that tickles your fancy.</p>
    <p>D. Gray</p>
</div>
{% endblock %}

home/templates/contact.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}Contact Gray and Sons{% endblock %}
{% block page_heading %}Contact Us{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <p class="font-weight-bold">general enquiries<br>
            <a href="">enquiries@graysauctionhouse.co.uk</a><br>
            <a href="">+44 (0)20 1234 5678</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p class="text-center  font-weight-bold">customer service<br>
            <a href="">customer-service@graysauctionhouse.co.uk</a><br>
            <a href="">+44 (0)20 1234 5678</a></p>
        </div>
    </div>
    <div class="row">
            <div class="col">
                <p class="text-right  font-weight-bold">Gray and Sons Auctionhouse<br>
                34 Tite Street<br>
                London<br>
                SW3 4JA</p>
            </div>
        </div>
</div>

{% endblock %}

home/templates/faq.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}About Gray and Sons{% endblock %}
{% block page_heading %}Frequently asked Questions{% endblock %}
{% block content %}

<div class="container-fluid">
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

    <p class="lead">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

    <p class="lead">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

</div>
{% endblock %}

home/templates/how-to.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}About Gray and Sons{% endblock %}
{% block page_heading %}How to Bid in an Auction{% endblock %}
{% block content %}

<div class="container-fluid">
   <p>We do try to make sure bidding is as simple as possible. To bid you <emphasis>must</emphasis> be a registered user and logged in.</p>
   <p>Simply view the item that interests you and click the bid button. This will open the bidding form. You will be shown what the current bid is and can enter your bid.</p>
   <p>You will not be able to see the names of other bidders but you will see your name if the leading bid is yours. You will also be notified by email of any auction you win with further details.</p>
</div>
{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}Gray and Sons{% endblock %}
{% block page_heading %}Gray and Sons Auction House{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="header-bg-img" style="background-image: url('{{ newest_picture.image.url }}')">
            <div class="bottom">
                <p class="ml-3  contrast-bg"><a href="{% url 'catalogue:catalogue-one' newest_picture.id %}">Details</a></p>
            </div>
        </div>
    </div>
</div>
    
<div class="row">
    {% for blog in top_two_blogs %}
        <div class="col-12  col-md-6">
            <h3 class="px-1">{{ blog.title }} <small class="text-muted">{{ blog.pub_date | date:"D d M Y" }}</small></h3>
            <p>{{ blog.text }}</p>
            {% if blog.image %}
                <img class="blog-img  py-2" src="{{ blog.image.url }}" alt="{{ blog.title }} picture.">
            {% endif%}
        </div>
    {% endfor %}
</div>
{% endblock %}

home/templates/shipping.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block page_title %}About Gray and Sons{% endblock %}
{% block page_heading %}Shipping{% endblock %}
{% block content %}

<div class="container-fluid">
    <p>Shipping is by courier service unless otherwise requested.</p>
    <p>For international deliveries there may be delays for customs. We will be happy to advise customers based on the specific details of the particular product and the destination.</p>
    <p>Please be aware import restrictions vary from country to country while we will be happy to work with you we must advise you to ensure you understand the restrictions your country places on the import or ownership of the item you intend to buy before purchase, especially in the case of items such as swords.</p>
</div>
{% endblock %}