auctionhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.urls import login, logout, register
from news.models import News, Review
from catalogue import urls as catalogue_urls
from catalogue.views import view_all, view_era, view_one
from catalogue.models import Catalogue
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('register', register, name="register"),
    path('', include('news.urls')),
    url(r'^auctions/', include(catalogue_urls)),
    path('', include('payment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import index, about, contact, faq, how_to, shipping
from catalogue.models import Catalogue

app_name = 'home'
urlpatterns = [
    path('', index, name="index"),
    path('about', about, name="about"),
    path('contact', contact, name="contact"),
    path('FAQ', faq, name="faq"),
    path('how-to', how_to, name="how_to"),
    path('shipping', shipping, name="shipping"),
]

payment/urls.py
from django.urls import path, include
from .views import billing, payment, charge
from .models import Billing_Address, Delivery_Address
from .forms import Billing_Address_Form, Delivery_Address_Form

app_name = 'payment'
urlpatterns = [
    path('bill<id>', billing, name="billing"),
    path('pay<id>', payment, name="payment"),
    path('success<id>', charge, name="paid")
]

payment/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Billing_Address(models.Model):
    PROF = 'Prof'
    DR = 'Dr'
    LADY = 'Lady'
    MRS = 'Mrs'
    MS = 'Ms'
    MISS = 'Miss'
    MR = 'Mr'
    SIR = 'Sir'
    TITLE_CHOICES = [
        (PROF, 'Prof'),
        (DR, 'Dr'),
        (LADY, 'Lady'),
        (MRS, 'Mrs'),
        (MS, 'Ms'),
        (MISS, 'Miss'),
        (MR, 'Mr'),
        (SIR, 'Sir'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=4, choices=TITLE_CHOICES, default=MRS)
    billing_name = models.CharField(max_length=80)
    street1 = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True)
    town = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    postcode = models.CharField(max_length=20)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.billing_name


class Delivery_Address(models.Model):
    PROF = 'Prof'
    DR = 'Dr'
    LADY = 'Lady'
    MRS = 'Mrs'
    MS = 'Ms'
    MISS = 'Miss'
    MR = 'Mr'
    SIR = 'Sir'
    TITLE_CHOICES = [
        (PROF, 'Prof'),
        (DR, 'Dr'),
        (LADY, 'Lady'),
        (MRS, 'Mrs'),
        (MS, 'Ms'),
        (MISS, 'Miss'),
        (MR, 'Mr'),
        (SIR, 'Sir'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=4, choices=TITLE_CHOICES, default=MRS)
    delivery_name = models.CharField(max_length=100)
    street1 = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True)
    town = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    postcode = models.CharField(max_length=20)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.delivery_name

payment/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Billing_Address, Delivery_Address


class Billing_Address_Form(ModelForm):
    class Meta:
        model = Billing_Address
        fields = [
            'title',
            'billing_name',
            'street1',
            'street2',
            'town',
            'county',
            'postcode',
            'country'
        ]


class Delivery_Address_Form(ModelForm):
    class Meta:
        model = Delivery_Address
        labels = {'delivery_name': 'Recipient\'s name'}
        fields = [
            'title',
            'delivery_name',
            'street1',
            'street2',
            'town',
            'county',
            'postcode',
            'country'
        ]


class RecipientModelChoiceField(forms.ModelChoiceField):
    """Pick a recipient from multiple delivery addresses"""
    def label_from_instance(self, address):
        return f"{address.delivery_name}, {address.street1}"


class Recipient_Form(forms.Form):
    recipient = RecipientModelChoiceField(
        queryset=None,
        widget=forms.RadioSelect,
        empty_label=None
    )

    def __init__(self, *args, user=None, **kwargs):
        if user is None:
            raise ValueError("Missing user")
        super().__init__(*args, **kwargs)
        self.fields['recipient'].queryset = Delivery_Address.objects.filter(user=user)

    def clean_recipient(self):
        recipient = self.cleaned_data.get('recipient')
        return recipient

payment/views.py
import os
import stripe

from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from .forms import Billing_Address_Form, Delivery_Address_Form,  Recipient_Form
from .models import Delivery_Address, Billing_Address
from catalogue.models import Catalogue

@login_required(login_url='/login/')
def billing(request, id):
    """Displays registered billing address for confirmation or blank form for a new address."""
    form_data = request.POST or None
    try:
        instance =  Billing_Address.objects.get(user=request.user)
    except ObjectDoesNotExist:
        instance = None
    billing_form = Billing_Address_Form(form_data, instance=instance)

    if request.method == "POST":
        if billing_form.is_valid():
            billing_address = billing_form.save(commit=False)
            billing_address.user = request.user
            billing_address.save()
            return redirect('payment:payment', id=id)

    return render(request, "billing-address.html", {"billing_form": billing_form})


@login_required(login_url='/login/')
def payment(request, id):

    """Allows selection or entry of delivery address, displays addresses, item details and stripe payment form."""
    form_data = request.POST or None
    recipient_form = Recipient_Form(form_data, user=request.user)
    delivery_form = Delivery_Address_Form(form_data)
    billing = Billing_Address.objects.get(user=request.user)
    item = Catalogue.objects.get(id=id)

    # if there is a selected delivery address
    if request.method == "POST":
        if delivery_form.is_valid():
            address_used = delivery_form.save(commit=False)
            address_used.user = request.user
            address_used.save()
            return render(
                request,
                "payment-details.html",
                {"address": address_used,
                "billing": billing,
                "item": item},
            )

        elif recipient_form.is_valid():
            address = recipient_form.cleaned_data.get("recipient")
            return render(
                request,
                "payment-details.html",
                {"address": address,
                "billing": billing,
                "item": item},
            )

    # if there is not a selected delivery address.
    recipient_check = Delivery_Address.objects.filter(user=request.user)
    if recipient_check:
        context = {"recipient_form": recipient_form, "delivery_form": delivery_form}
    else:
        context = {"delivery_form": delivery_form}
    return render(request, "delivery-address.html", context)


@login_required(login_url='/login/')
def charge(request, id):
    item = Catalogue.objects.get(id=id)
    stripe.api_key = os.getenv("STRIPE_SECRET")
    if request.method == 'POST':
        token = request.POST.get('stripeToken')
        charge = stripe.Charge.create(
                amount=int(item.bid) * 100,
                currency='gbp',
                description=item.name,
                source=token,
            )

        if charge.paid:
            return render(request, "success.html", {"item": item})
            
        else:
            messages.error(request, f"Your card was declined!")

    return redirect('payment:payment', id=id)

payment/templates/billing-address.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block page_title %}Gray and Sons{% endblock %}
{% block page_heading %}Add a billing address{% endblock %}
{% block content %}

<form method="POST">
    <div class="border  border-primary  enclose">
        <h4 class="pt-2  ml-2">Billing Address</h4>
        <div class="ml-2">
                {% csrf_token %}
                {{ billing_form | crispy }}
                <button type="submit" class="btn btn-primary  my-2  ml-2">On to Delivery Address</button>
        </div>
    </div>
</form>

{% endblock %}

payment/templates/delivery-address.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block page_title %}Gray and Sons{% endblock %}
{% block page_heading %}Select a Delivery Address{% endblock %}
{% block content %}

<div class="border  border-primary  enclose">
<form method="POST" novalidate>
    {% csrf_token %}

    <h4 class="pt-2  ml-2">Delivery Address <small class="text-muted">Step 2 of 3</small></h4>
    <div class="ml-2">
        {{ recipient_form | crispy }}
    </div>

    <button type="button" class="btn  btn-outline-primary  d-block  my-3  ml-2" onclick="toggleFormDisplay('delivery')">Add a recipient.</button>

    <div id="delivery" class="d-none  ml-2">
        {{ delivery_form | crispy }}
    </div>

    <button type="submit" class="btn  btn-primary  my-2  ml-2">To payment
    </button>

</form>
</div>

{% endblock %}

{% block script %}
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

payment/templates/payment-details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}

{% block stripe-css %}
<link rel="stylesheet" href="{% static 'vendor/css/stripe.css' %}" type="text/css">
{% endblock %}

{% block page_title %}Gray and Sons - Payment{% endblock %}
{% block page_heading %}Payment Details{% endblock %}
{% block content %}

<div class="border  border-primary  enclose">
<div class="row">
    <div class="col"><h4 class="pt-2  ml-2">Delivery Address <small class="text-muted">Step 3 of 3</small></h4></div>
</div>
    <div class="row">
        <div class="col  col-md-5  offset-md-1">
            <p>{{ address.title | title }} {{ address.delivery_name | title }}<br>
            {{ address.street1 | title}}<br>
            {% if address.street2 %}
                {{ address.street2 | title}}<br>
            {% endif %}
            {{ address.town | title}}<br>
            {{ address.county | title}}<br>
            {{ address.postcode | title}}<br>
            {{ address.country | title}}<br>
            </p>
        </div>
        <div class="col  col-md-6">
            <p>
                {{ billing.billing_name | title }}<br>
                {{ billing.street1 | title}}<br>
                {% if billing.street2 %}
                    {{ billing.street2 | title}}<br>
                {% endif %}
                {{ billing.town | title}}<br>
                {{ billing.county | title}}<br>
                {{ billing.postcode | title}}<br>
                {{ billing.country | title}}<br>
            </p>
        </div>
    </div>
</div>

<div class="border  border-primary  enclose  mt-2">
    <div class="row">
        <div class="col  col-offset-1  ml-2">
            <p class="pl-2">
                {{ item.name | title }} &#163;{{ item.bid }}
            </p>
        </div>
    </div>
</div>

<div class="border  border-primary  enclose  mt-2">
  <form action="{% url 'payment:paid' item.id %}" method="POST" id="payment-form">
        <div>
            {% csrf_token %}
            <label for="card-element" class="pt-2  ml-2">
            Credit or debit card
            </label>
            <div class="mx-2" id="card-element">
                <!-- A Stripe Element will be inserted here. -->
            </div>
            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>
        <button class="my-2 ml-2">Submit Payment</button>
  </form>
</div>

<a href="{% url 'payment:billing' item.id %}">Back</a>

<script>
// Create a Stripe client.
var stripe = Stripe('pk_test_WMQVmCtHBkXuxzLApLOM8AkW00G5XbFZ23');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>

{% endblock %}

payment/templates/success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}

{% block page_title %}Gray and Sons{% endblock %}
{% block page_heading %}Payment Successful{% endblock %}
{% block content %}

<p>Your payment of {{ item.bid }}has been made, {{ item.name }} will be dispatched to you as soon as possible. Thank you for your business we look forwards to seeing you at future auctions.</p>

{% endblock %}