auctionhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.urls import login, logout, register
from news.models import News, Review
from catalogue import urls as catalogue_urls
from catalogue.views import view_all, view_era, view_one
from catalogue.models import Catalogue
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('register', register, name="register"),
    path('', include('news.urls')),
    url(r'^auctions/', include(catalogue_urls)),
    path('', include('payment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from .views import view_all, view_era, view_one
from .models import Catalogue

app_name = 'catalogue'
urlpatterns = [      
    url(r'^$', view_all, name="catalogue-all"),      
    url(r'^era(\d+)', view_era, name='view_era'),      
    url(r'^item/(\d+)', view_one, name="catalogue-one")
] 

home/urls.py
from django.urls import path
from .views import index, about, contact, faq, how_to, shipping
from catalogue.models import Catalogue

app_name = 'home'
urlpatterns = [
    path('', index, name="index"),
    path('about', about, name="about"),
    path('contact', contact, name="contact"),
    path('FAQ', faq, name="faq"),
    path('how-to', how_to, name="how_to"),
    path('shipping', shipping, name="shipping"),
]

news/urls.py
from django.urls import path
from .views import news, reviews
from .models import News, Review

app_name = 'blog'
urlpatterns = [
    path('news', news, name="news"),
    path('reviews', reviews, name="reviews"),
]

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block page_title %}{% endblock %}</title>

    <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}" type="text/css">
    {% block stripe-css %}{% endblock %}

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'realfavicongenerator/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'realfavicongenerator/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'realfavicongenerator/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'realfavicongenerator/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'realfavicongenerator/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <script defer src="{% static 'js/fontawesome-all.min.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
     
</head>
<body>
    
    <nav class="container-fluid  navbar-expand-lg  navbar-light  bg-light">
        <div class="row">
            <div class="col-2">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div class="col">
                <p class="title"><a class="navbar-brand  title" href="{% url 'home:index' %}">Grays Auction House</a></p>
            </div>

            <div class="col-4">
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="navbar-text">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}" class="navbar-text">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="row">
            <div class="col-12">
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'catalogue:catalogue-all' %}">Auctions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:news' %}">News</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:reviews' %}">Reviews</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:how_to' %}">How it Works</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <section id="time-categories" class="container-fluid">
        <div class="row">
            <div class="col  time-select">
                <a href="{% url 'catalogue:view_era' 1 %}" class="selected-link"><p class="text-center">Early Medieval</p></a>
            </div>
            <div class="col  time-select">
                <a href="{% url 'catalogue:view_era' 2 %}" class="selected-link">
                    <p class="text-center">17th Century</p>
                </a>
            </div>
            <div class="col  time-select">
                <a href="{% url 'catalogue:view_era' 3 %}" class="selected-link">
                    <p class="text-center">18th Century</p>
                </a>
            </div>
            <div class="col  time-select">
                <a href="{% url 'catalogue:view_era' 4 %}" class="selected-link">
                    <p class="text-center">Victorian</p>
                </a>
            </div>
        </div>
    </section>

    <section>
        {% if messages %}
            {% for message in messages %} 
                <div class="alert  alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %} 
    </section>

    <main class="container-fluid">
            <h1>{% block page_heading %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
    </main>
    
    <footer class="container-fluid">
        <div class="row">
            <div class="col">
                <p class="text-center"><a href="https://www.facebook.com" target="_blank" rel="noopener"><span><i class="fab  fa-facebook-square  facebook"></i></span></a></p>
            </div>
            <div class="col">
                <p class="text-center"><a href="https://twitter.com/" target="_blank" rel="noopener"><span><i class="fab  fa-twitter  twitter"></i></span></a></p>
            </div>
        </div>

        <div class="row">
            <div class="col-12  col-md-6">
                <p>
                    <button class="btn" type="button" data-toggle="collapse" data-target="#aboutUs" aria-expanded="false" aria-controls="aboutUs">
                        About Us <i class="fas fa-caret-down"></i>
                    </button>
                </p>
                <div class="collapse" id="aboutUs">
                    <div>
                        <a class="px-3" href="{% url 'home:about' %}">About Us</a><br>
                        <a class="px-3" href="{% url 'home:contact' %}">Contact Us</a>
                    </div>
                </div>
            </div>
            <div class="col-12  col-md-6">
                <p>
                    <button class="btn" type="button" data-toggle="collapse" data-target="#resources" aria-expanded="false" aria-controls="resources">
                        Resources <i class="fas fa-caret-down"></i>
                    </button>
                </p>
                <div class="collapse" id="resources">
                    <div>
                        <a href="{% url 'home:faq' %}">Help and FAQ's</a><br>
                        <a href="{% url 'home:how_to' %}">Bidding in an Auction</a><br>
                        <a href="{% url 'home:shipping' %}">Shipping</a><br>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col">
                <p class="left-13"><small><a target="_blank" rel="noopener" href="https://gdpr.eu/wp-content/uploads/2019/01/Our-Company-Privacy-Policy.pdf">Privacy Policy</a></small></p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p class="text-center"><small><span><i class="far fa-copyright"></i></span> Copyright Gray and Sons 2019</small></p>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}

</body>
</html>